# backend = full | resized | wal | thumb | fastresize | kmeans
palette = "dark"
check_contrast = true

[templates]
hypr = { src = "hyprland.conf", dst = "~/.config/hypr/colors.conf" }
waybar = { src = "waybar.css", dst = "~/.config/waybar/colors.css" }
kitty = { src = "kitty.conf", dst = "~/.config/kitty/colors.conf" }
rofi = { src = "rofi.rasi", dst = "~/.config/rofi/colors.rasi" }
nvim = { src = "nvim.vim", dst = "~/.cache/wal/colors-wal.vim" }
